app/app/article/forms.py
#coding:utf8
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, TextAreaField, BooleanField, SelectField,\
    SubmitField
from wtforms.validators import Required, Length, Email, Regexp
from ..models import Role,User
from flask_pagedown.fields import PageDownField

class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[Required()])
    submit = SubmitField('Submit')

class PostForm(FlaskForm):
    title = StringField('title', validators=[Required()])
    body = TextAreaField("write something",validators=[Required()])
    submit = SubmitField('submit')

class CommentForm(FlaskForm):
    body = StringField('',validators=[Required()])
    submit = SubmitField('submit')
        

app/app/article/__init__.py
from flask import Blueprint

article = Blueprint('article',__name__)

from . import views

app/app/article/views.py
# coding:utf8
from flask import (abort, current_app, flash, redirect, render_template,
                   request, session, url_for)
from flask_login import current_user, login_required
from werkzeug import secure_filename

from . import article
from .. import db
from ..decorators import admin_required, permission_required
from ..email import send_email
from ..models import Comment, Permission, Post, Role, User
from .forms import CommentForm, NameForm, PostForm


@article.route('/index', methods=['GET', 'POST'])
def index():
    form = PostForm()
    # 分页
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=20, error_out=False)
    posts = pagination.items
    return render_template('article/index.html', form=form, posts=posts, pagination=pagination)


@article.route('/list', methods=['GET', 'POST'])
def list():
    form = PostForm()

    # 分页
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=20, error_out=False)
    posts = pagination.items
    return render_template('article/article-list.html', form=form, posts=posts, pagination=pagination)


@article.route('/postArticle', methods=['GET', 'POST'])
@login_required
def postArticle():
    form = PostForm()
    if current_user.can(Permission.WRITE_ARTICLES) and \
            form.validate_on_submit():
        post = Post(title=form.title.data,
                    body=form.body.data,
                    author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('article.postArticle'))
    return render_template('article/post_article.html', form=form)


@article.route('/cv<int:id>', methods=['GET', 'POST'])
def cv(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        flash('Your comment has been published.')
        return redirect(url_for('.post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) / 20 + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=20, error_out=False)
    comments = pagination.items
    return render_template('post.html', posts=[post], form=form,
                           comments=comments, pagination=pagination)


@article.route('/edit/cv<int:id>', methods=['GET', 'POST'])
@login_required
def editArticle(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and not current_user.can(Permission.ADMINISTER):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        db.session.add(post)
        flash("The post has been updated.")
    form.title.data = post.title
    form.body.data = post.body
    return render_template('edit_post.html', form=form, posts=[post])

app/app/templates/article/_postform.html
<script type="text/javascript" src="{{ url_for('static',filename='js/wangeditor/wangEditor.js') }}"></script>
<div class="post-article">
	<form method="POST">
		<div class="cover-img">
			
		</div>
		{{ form.csrf_token }}
		<h1>标题*</h1>
		{{ form.title(class="title-form") }}
		{{ form.body(id="editor2",class="RichTextEditor") }} 
		<div id="editor">
			<p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
		</div>
		{{ form.submit(class="submit") }} 
	</form>
</div>
<!--wangeditor V3版本后不支持使用textarea。在此用onchang方法同步内容-->
<script type="text/javascript">
	var E = window.wangEditor
	var editor = new E('#editor')
	var $text1 = $('#editor2')
	editor.customConfig.onchange = function (html) {
		// 监控变化，同步更新到 textarea
		$text1.val(html)
	}
	//窗口zindex值，不设置时默认10000
	editor.customConfig.zIndex = 1
	editor.create()
	// 初始化 textarea 的值
	$text1.val(editor.txt.html())
</script>

app/app/templates/article/article-list.html
{% extends "layout.html" %}
{% import "_macros.html" as macros %}
 
{% block title %}Flasky{% endblock %}
{% block head %}
{{ super() }}

{% endblock %}
{% block wrapper %}

{% include '_posts.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'article.list') }}
</div>
{% endif %}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/app/templates/article/index.html
{% extends "layout.html" %}
{% import "_macros.html" as macros %}
 
{% block title %}Flasky{% endblock %}
{% block head %}
{{ super() }}

{% endblock %}
{% block wrapper %}
	<div class="article">
		<div class="aside">
		</div>
		<div class="page-content">
			<div class="article-list">
				<div class="article-list-holder">
					{% for post in posts %}
						<div class="article-item">
							<div class="item-holder">
								<div class="article-content">
									<div class="article-left-block">
										<a class="article-title" href="{{ url_for('article.cv', id=post.id) }}">{{ post.title }}</a>
										<div class="article-desc">
											{% if post.body_html %}
												{{ post.body_html | safe }}
											{% else %}
												{{ post.body }}
											{% endif %}
										</div>
										<div class="article-info-bar">
											<a href="" class="up-content">
												<span class="face-holder"><img src="{{ post.author.getavatar() }}"></img></span>
												<span class="nick-name">{{ post.author.username }}</span>
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
			{% if pagination %}
			<div class="pagination">
				{{ macros.pagination_widget(pagination, 'article.list') }}
			</div>
		</div>
	</div>
{% endif %}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/app/templates/article/post_article.html
{% extends "layout.html" %}
{% import "_macros.html" as macros %}
 
{% block title %}Flasky{% endblock %}
{% block head %}
{{ super() }}

{% endblock %}
{% block wrapper %}

{% include 'article/_postform.html' %}

{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}