app/app/spider/__init__.py
from flask import Blueprint

spider = Blueprint('spider',__name__)

from . import views

app/app/spider/views.py
from flask import render_template,redirect,url_for
from . import spider
from flask_login import login_required, current_user
from ..decorators import admin_required
from imgspider import imgSpider
@spider.route('/index',methods=['GET','POST'])
def index():
    return render_template("spider/index.html")

@spider.route('/qiubai/<int:page_id>',methods=['GET','POST'])
def qiubai(page_id):
    url=r'http://qiubaichengren.com/%s.html'%page_id
    reg=r'<img alt="(.+?)" src="(\S+?)" style='
    imglist=imgSpider(url,reg).getImgList()
    imglist2=[]
    for i,j in enumerate(imglist):
        x=[j[0].decode('gbk'),j[1]]
        imglist2.append(x)
    return render_template("spider/spider.html",imglist2=imglist2,page_id=page_id)
    
@spider.route('/qiubaiwep/<int:page_id>',methods=['GET','POST'])
def qiubaiwep(page_id):
    url=r'http://qiubaichengren.com/%s.html'%page_id
    reg=r'<img alt="(.+?)" src="(\S+?)" style='
    imglist=imgSpider(url,reg).getImgList()
    imglist2=[]
    for i,j in enumerate(imglist):
        x=[j[0].decode('gbk'),j[1]]
        imglist2.append(x)
    return render_template("spider/spiderwep.html",imglist2=imglist2,page_id=page_id)


@spider.route('/cmm/<int:page_id>',methods=['GET','POST'])
def cmm(page_id):
    url=r'http://www.qiushimm.com/page/%s'%page_id
    reg=r'<img.+?src="(\S+?)" alt="(.+?)"'
    imglist=imgSpider(url,reg).getImgList()
    imglist2=[]
    for i,j in enumerate(imglist):
        x=[j[1].decode('utf8'),j[0]]
        imglist2.append(x)
    return render_template("spider/img.html",imglist2=imglist2,page_id=page_id)

app/app/templates/spider/content.html
	<ul class="posts">
		{% for i,j in imglist2 %}
		<li class="post">
			<div class="post-head">
				<a href="{{ url_for('main.user', username=current_user.username) }}">
					<img class="img-rounded profile-thumbnail" src="{{ url_for('static', filename='tou.png') }}" width="40" height="40">
				</a>
			</div>
			<div class="post-content">
				<div class="post-author"><a href="">ID3055</a></div>
				<div class="post-body"><p>{{ i }}</p><img src= {{ j }} /></div>

			</div>
		</li>
		{% endfor %}
	</ul>
	<div class="buttom1">  
	{% if page_id>=5 %}    
		<div class='page3'>第</div>
		<a href=1 ><div class='page1' >1</div></a>
		<div class='page3'>...</div>
		{% for t in range(page_id-2,page_id+3) %} 
			{% if page_id==t %}
				<div class='page2' >{{ t }}</div>
			{% else %}
				<a href={{ t }} ><div class='page1' >{{ t }}</div></a>
			{% endif %}
		{% endfor %}
		<div class='page3'>页</div>
	{% else %}
		<div class='page3'>第</div>
		{% for t in range(1,6) %} 
			{% if page_id==t %}
				<div class='page2' >{{ t }}</div>
			{% else %}
				<a href={{ t }} ><div class='page1' >{{ t }}</div></a>
			{% endif %}
		{% endfor %}
		<div class='page3'>页</div>
	{% endif %}
	</div>

app/app/templates/spider/index.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky{% endblock %}

{% block wrapper %}
<a href="{{ url_for('spider.qiubai',page_id=1) }}">qiubai</a>
{% endblock %}

app/app/templates/spider/spider.html
{% extends "layout.html" %}

{% block title %}Flasky{% endblock %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static',filename='css/spider.css') }}" type="text/css" media="screen,projection" />
{% endblock %}
{% block wrapper %}
<div class=".bili-content-wrapper clearfix">
	<div class="wiki-aside clearfix">
		<p><strong>站点</strong></p>
		<ul>
			<li><a href="/spider/qiubai/1">QiuBai</a></li>
			<li><a href="/spider/qiubaiwep/1">手机</a></li>
		</ul>
	</div>
	<div class="wiki-content clearfix">
		{% include 'spider/content.html' %}
	</div>
</div>
{% endblock %}

app/app/templates/spider/spiderwep.html
{% extends "base.html" %}

{% block title %}Flasky{% endblock %}
{% block head %}
{{ super() }}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='css/spider.css') }}" type="text/css" media="screen,projection" />
{% endblock %}
{% block content %}
<div class=".bili-content-wrapper clearfix">
	{% include 'spider/content.html' %}
</div>
{% endblock %}